### PR TITLE
Allow using directory as target.

### PR DESCRIPTION
**Pull request by account-login**
Fixes the problem of can not remove directory targets.

### CODE REVIEW

**Comment by zwegner** [comment]
I merged this one too.

I wonder if shutil.rmtree is the right option here though, rather than os.rmdir? The latter will throw an exception if the directory is not empty. Would that work in your use case? The concern with rmtree would be deleting important files if a rule is created that accidentally leaves off the last component of a target. Though generally it will be in the output directory, so probably not a big deal.

**Comment by account-login** [comment]
What about limit rmtree to the output directory? In my use case, the target directory is non-empty, but I do agree that rmtree outside the output directory is dangerous.

**Comment by zwegner** [comment]
That seems like a good compromise for now. I'm not a huge fan of the special meaning assigned to _out, but that dates back to before I took over maintainership.

Do you know an easy way to check for whether a file is below a directory? Maybe `os.path.abspath(f).startswith(os.path.abspath(d) + '/')`?

Also, it's probably a good idea to unconditionally try `os.unlink()` first, and only check for a directory if an exception is raised, so the common case only uses one syscall instead of three (a la `get_timestamp_if_exists()`).

**Comment by account-login** [comment]
As for checking for whether a file is below a directory, I think `os.path.realpath` is better than `os.path.abspath` since the latter resolves symbolic links. (Consider the case `_out/a/b/` where `a` is a symbolic link points to somewhere outside `_out`.)
I'm not sure about whether `os.path.normcase` should be used to handle case-insensitive filesystems.

Failing to detect that a path is below a directory only results in failing to delete files, so `os.path.realpath(f).startswith(os.path.realpath(d) + os.sep)` is probably enough to go.

**Comment by zwegner** [comment]
(sorry, forgot to respond here earlier)

So I went along the path you suggested and found this is a bit more complicated than I thought, since there can be multiple _out directories when you have multiple rules.py files. I think I have it mostly worked out, but I want to make sure that I understand the use case for this feature, in case there's an easier way to handle it. What are you using directory targets for? Is it possible to use a dummy file in the directory, or a 'mkdir' as an initial command in the rule?

**Comment by account-login** [comment]
My use case is that I am using `lcov` to generate a directory that contains multiple HTML files
and I did not bother to enumerate all the output files. I can use the dummy file approach that you have suggested and add a `rmdir` to the beginning of the rule. While the dummy file approach works, it feels like a workaround and is unintuitive to me.

The biggest advantage of `make.py` IMHO is that it is conceptually simple, a user can fully understand what it does and how to use it by looking at the `ctx.add_rule` function, no documentation is needed.
So I think it would be valuable to support the directory target use case and eliminate the need for a workaround.

**Comment by zwegner** [comment]
Sounds pretty reasonable to me. I added the relevant code, opting for a warning in case the directory isn't in _out. Let me know if you have any problems with it.

**Pull request closed without merging**
